# docker-compose.yml
version: '2.20.2'

services:
  web:
    build: ./
    command: gunicorn gems.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_vol:/app/static
    expose:
      - 8000
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_vol:/app/static
    depends_on:
      - web

volumes:
  static_vol: