# Generated by Django 4.2.4 on 2023-08-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=256, verbose_name='Покупатель')),
                ('stone_type', models.CharField(max_length=256, verbose_name='Вид камня')),
                ('total_price', models.PositiveIntegerField(verbose_name='Сумма сделки')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
    ]
